Models/ViewModels/GameMatch.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ProjectPrototype.Models;
using System.ComponentModel;

namespace ProjectPrototype.ViewModels
{
    public class GameMatch
    {
        public Game Game { get; set; }
        public Match MatchW { get; set; }

        public Team TeamW { get; set; }
        public Match MatchL { get; set; }
        public Team TeamL { get; set; }

        public GameMatch()
        {

        }
    }

    public class GameMatchStats : GameMatch
    {
        [DisplayName("Select Team")]
        public int? SelectedTeamId { get; set; }
        [DisplayName("Select Player")]
        public int? SelectedPlayerId { get; set; }

        public Player SelectedPlayer { get; set; }

        public Player DummyPlayer { get; set; }
        public GameMatchStats()
        {

        }
    }
}

Areas/Admin/Controllers/GameMatchController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ProjectPrototype.Controllers;
using ProjectPrototype.ViewModels;
using ProjectPrototype.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ProjectPrototype.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class GameMatchController : Controller
    {

        private readonly RosterContext _context;

        public GameMatchController(RosterContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {

            /*var result =  await _context.Matches
                .GroupBy(m => m.GameId)
                .Select(m => new { m.Key, m2 = m})
                .ToDictionaryAsync(m => m.Key, m => m.m2);*/

            // Manual groupings cause LINQ dumb
            Dictionary<int, List<Match>> groups = new Dictionary<int, List<Match>>();
            foreach (var match in _context.Matches)
            {
                // Hack to fill in object references
                match.Game = _context.Games.Find(match.GameId);
                match.Team = _context.Teams.Find(match.TeamId);
                _context.Matches.Update(match);
                

                if (!groups.ContainsKey(match.GameId))
                    groups.Add(match.GameId, new List<Match>());
                groups[match.GameId].Add(match);

            }

            await _context.SaveChangesAsync();

            List<GameMatch> fullGames = new List<GameMatch>();
            // Iterate over match groupings
            foreach (var groupings in groups)
            {
            // Check if grouping has 2 matches (it should always)
                Match a = groupings.Value.ElementAt(0);
                Match b = groupings.Value.ElementAt(1);
                var fullGame = DetermineGameWinner(a, b);
                if (fullGame != null)
                    fullGames.Add(fullGame);
            }
            return View(fullGames);
        }

        [HttpPost]
        public async Task<IActionResult> Index(string SearchString)
        {
            if (SearchString == null)
                SearchString = "";

            // Manual groupings cause LINQ dumb
            Dictionary<int, List<Match>> groups = new Dictionary<int, List<Match>>();
            foreach (var match in _context.Matches)
            {

                match.Game = _context.Games.Find(match.GameId);
                match.Team = _context.Teams.Find(match.TeamId);

                if (!Util.UseSearchTerm(SearchString, match.Team.TeamName))
                    continue;

                if (!groups.ContainsKey(match.GameId))
                {
                    groups.Add(match.GameId, new List<Match>());
                }
                // group made
                groups[match.GameId].Add(match);
                
            }

            // Second pass to add non search pair
            foreach(var match in _context.Matches)
            {
                if(groups.ContainsKey(match.GameId) && groups[match.GameId].Count < 2 && groups[match.GameId].ElementAt(0).TeamId != match.TeamId)
                {
                    // group made, and only 1 element
                    // Add other
                    groups[match.GameId].Add(match);
                }
            }

            List<GameMatch> fullGames = new List<GameMatch>();
            // Iterate over match groupings
            foreach (var groupings in groups)
            {
                // Check if grouping has 2 matches (it should always)
                Match a = groupings.Value.ElementAt(0);
                Match b = groupings.Value.ElementAt(1);
                var fullGame = DetermineGameWinner(a, b);
                if (fullGame != null)
                    fullGames.Add(fullGame);
            }
            return View(fullGames);
        }

        private GameMatch DetermineGameWinner(Match a, Match b)
        {
            GameMatch g = new GameMatch();
            if (a.Score >= b.Score)
            {
                g.MatchW = a;
                g.MatchL = b;
                // A is winner/Tie
            }
            else if (a.Score < b.Score)
            {
                // B is Winner
                g.MatchW = b;
                g.MatchL = a;
            }
            g.Game = a.Game;
            g.TeamW = _context.Teams.FirstOrDefault(t => t.TeamId == g.MatchW.TeamId);
            g.TeamL = _context.Teams.FirstOrDefault(t => t.TeamId == g.MatchL.TeamId);
            return g;
        }

        // GET: Players/Create
        public IActionResult Create()
        {
            ViewData["TeamIdA"] = new SelectList(_context.Teams, "TeamId", "TeamName");
            ViewData["TeamIdB"] = new SelectList(_context.Teams, "TeamId", "TeamName");
            return View();
        }

        // POST: Players/Create
        [HttpPost]
        public async Task<IActionResult> Create(GameMatch fullGame)
        {
            if (ModelState.IsValid)
            {
                // Add Game
                var trackGame = _context.Add(new Game
                {
                    DateTime = fullGame.Game.DateTime,
                    Location = fullGame.Game.Location
                });
                // Save so auto ID is generated
                await _context.SaveChangesAsync();

                Outcome outcomeA;
                Outcome outcomeB;
                if(fullGame.MatchW.Score > fullGame.MatchL.Score)
                {
                    outcomeA = Outcome.Win;
                    outcomeB = Outcome.Loss;
                }else if(fullGame.MatchW.Score > fullGame.MatchL.Score)
                {
                    outcomeA = Outcome.Loss;
                    outcomeB = Outcome.Win;
                }
                else
                {
                    outcomeA = Outcome.Tie;
                    outcomeB = Outcome.Tie;
                }

                // Add Matches
                _context.Add(new Match
                {
                    GameId = trackGame.Entity.GameId,
                    TeamId = fullGame.TeamW.TeamId,
                    Score = fullGame.MatchW.Score,
                    Outcome = outcomeA
                });
                _context.Add(new Match
                {
                    GameId = trackGame.Entity.GameId,
                    TeamId = fullGame.TeamL.TeamId,
                    Score = fullGame.MatchL.Score,
                    Outcome = outcomeB
                });
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["TeamIdA"] = new SelectList(_context.Teams, "TeamId", "TeamName", fullGame.MatchW.TeamId);
            ViewData["TeamIdB"] = new SelectList(_context.Teams, "TeamId", "TeamName", fullGame.MatchL.TeamId);
            return View(fullGame);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = await _context.Games.FindAsync(id);
            if (game == null)
            {
                return NotFound();
            }

            var matches = _context.Matches.Where(m => m.GameId == game.GameId).ToList();
            if(matches.Count() != 2)
            {
                return NotFound();
            }

            var a = matches.ElementAt(0);
            var b = matches.ElementAt(1);
            var gameMatch = DetermineGameWinner(a, b);

            ViewData["TeamIdA"] = new SelectList(_context.Teams, "TeamId", "TeamName", gameMatch.MatchW.TeamId);
            ViewData["TeamIdB"] = new SelectList(_context.Teams, "TeamId", "TeamName", gameMatch.MatchL.TeamId);
            return View(gameMatch);
        }

        // POST: Matches/Edit/5
        [HttpPost]
        public async Task<IActionResult> Edit(GameMatch fullGame)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var matchW = await _context.Matches.FirstOrDefaultAsync(m => m.MatchId == fullGame.MatchW.MatchId);
                    var matchL = await _context.Matches.FirstOrDefaultAsync(m => m.MatchId == fullGame.MatchL.MatchId);

                    if (matchW != default(Match) && matchL != default(Match))
                    {

                        matchW.Score = fullGame.MatchW.Score;
                        matchW.TeamId = fullGame.TeamW.TeamId;
                        matchL.Score = fullGame.MatchL.Score;
                        matchL.TeamId = fullGame.TeamL.TeamId;
                        _context.UpdateRange(matchW, matchL);

                        var game = await _context.Games.FirstOrDefaultAsync(g => g.GameId == fullGame.Game.GameId);

                        if(game != default(Game))
                        {
                            game.DateTime = fullGame.Game.DateTime;
                            game.Location = fullGame.Game.Location;

                            _context.Update(game);

                            await _context.SaveChangesAsync();
                        }
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.Games.Any(g => g.GameId == fullGame.Game.GameId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            // ModelState invalid
            ViewData["TeamIdA"] = new SelectList(_context.Teams, "TeamId", "TeamName", fullGame.MatchW.TeamId);
            ViewData["TeamIdB"] = new SelectList(_context.Teams, "TeamId", "TeamName", fullGame.MatchL.TeamId);

Areas/Admin/Views/GameMatch/Create.cshtml
@model ProjectPrototype.ViewModels.GameMatch

@{
    ViewData["Title"] = "Create Game";
}

<div class="container">
    <h1 class="table-title">Create Game</h1>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <input type="hidden" asp-for="TeamW.Mascot" value="fillerMascot" />
                    <input type="hidden" asp-for="TeamW.TeamName" value="fillerName" />
                    <label asp-for="TeamW.TeamId" class="control-label">Winner</label>
                    <select asp-for="TeamW.TeamId" class="form-control" asp-items="ViewBag.TeamIdA"></select>
                </div>
                <div class="form-group">
                    @Html.DisplayFor(model => model.MatchW.MatchId)
                    @Html.DisplayFor(model => model.MatchW.TeamId)
                    @Html.DisplayFor(model => model.MatchW.GameId)
                    <label asp-for="MatchW.Score" class="control-label">Winner Score</label>
                    <input asp-for="MatchW.Score" class="form-control" />
                    <span asp-validation-for="MatchW.Score" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="hidden" asp-for="TeamL.Mascot" value="fillerMascot" />
                    <input type="hidden" asp-for="TeamL.TeamName" value="fillerName" />
                    <label asp-for="TeamL.TeamId" class="control-label">Loser</label>
                    <select asp-for="TeamL.TeamId" class="form-control" asp-items="ViewBag.TeamIdB"></select>
                </div>
                <div class="form-group">
                    @Html.DisplayFor(model => model.MatchL.MatchId)
                    @Html.DisplayFor(model => model.MatchL.TeamId)
                    @Html.DisplayFor(model => model.MatchL.GameId)
                    <label asp-for="MatchL.Score" class="control-label">Loser Score</label>
                    <input asp-for="MatchL.Score" class="form-control" />
                    <span asp-validation-for="MatchL.Score" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Game.DateTime" class="control-label">Date/Time</label>
                    <input asp-for="Game.DateTime" class="form-control" />
                    <span asp-validation-for="Game.DateTime" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Game.Location" class="control-label"></label>
                    <input asp-for="Game.Location" class="form-control" />
                    <span asp-validation-for="Game.Location" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="table-management-button" />
                    <a class="table-management-button" asp-action="Index">Back To Games</a>
                </div>
            </form>
        </div>
    </div>
</div>

Areas/Admin/Views/GameMatch/Delete.cshtml
@model ProjectPrototype.ViewModels.GameMatch

@{
    ViewData["Title"] = "Delete Game";
}


<div class="container">
    <h4 class="table-title">Are you sure you want to delete this game?</h4>
    <div>
        <dl class="row">
            <dt class="col-sm-2">
                Winner
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.MatchW.Team.TeamName)
            </dd>
            <dt class="col-sm-2">
                Winner Score
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.MatchW.Score)
            </dd>
            <dt class="col-sm-2">
                Loser
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.MatchL.Team.TeamName)
            </dd>
            <dt class="col-sm-2">
                Loser Score
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.MatchL.Score)
            </dd>
            <dt class="col-sm-2">
                Date/Time
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Game.DateTime)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Game.Location)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Game.Location)
            </dd>
        </dl>
        <hr />
        <form asp-action="Delete">
            <input type="hidden" asp-for="Game.GameId" />
            <input type="submit" value="Delete" class="table-management-button" />
            <a class="table-management-button" asp-action="Index">Back to List</a>
        </form>
    </div>
</div>

Areas/Admin/Views/GameMatch/Edit.cshtml
@model ProjectPrototype.ViewModels.GameMatch

@{
    ViewData["Title"] = "Edit Game";
}

<div class="container">
    <h1 class="table-title">Edit Game</h1>
    <!-- This section should be at the top and show the Game datetime and location, and then the Team and their scores below/to the side-->
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    @Html.HiddenFor(model => model.TeamW.TeamName)
                    @Html.HiddenFor(model => model.TeamW.Mascot)
                    <label asp-for="TeamW.TeamId" class="control-label">Winner</label>
                    <select asp-for="TeamW.TeamId" class="form-control" asp-items="ViewBag.TeamIdA"></select>
                </div>
                <div class="form-group">
                    @Html.HiddenFor(model => model.MatchW.MatchId)
                    @Html.HiddenFor(model => model.MatchW.TeamId)
                    @Html.HiddenFor(model => model.MatchW.GameId)
                    <label asp-for="MatchW.Score" class="control-label">Winner Score</label>
                    <input asp-for="MatchW.Score" class="form-control" />
                    <span asp-validation-for="MatchW.Score" class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.HiddenFor(model => model.TeamL.TeamName)
                    @Html.HiddenFor(model => model.TeamL.Mascot)
                    <label asp-for="TeamL.TeamId" class="control-label">Loser</label>
                    <select asp-for="TeamL.TeamId" class="form-control" asp-items="ViewBag.TeamIdB"></select>
                </div>
                <div class="form-group">
                    @Html.HiddenFor(model => model.MatchL.MatchId)
                    @Html.HiddenFor(model => model.MatchL.TeamId)
                    @Html.HiddenFor(model => model.MatchL.GameId)
                    <label asp-for="MatchL.Score" class="control-label">Loser Score</label>
                    <input asp-for="MatchL.Score" class="form-control" />
                    <span asp-validation-for="MatchL.Score" class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.HiddenFor(model => model.Game.GameId)
                    <label asp-for="Game.DateTime" class="control-label">Date/Time</label>
                    <input asp-for="Game.DateTime" class="form-control" />
                    <span asp-validation-for="Game.DateTime" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Game.Location" class="control-label">Location</label>
                    <input asp-for="Game.Location" class="form-control" />
                    <span asp-validation-for="Game.Location" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="table-management-button" />
                    <a class="table-management-button" asp-action="Index">Back To Games</a>
                </div>
            </form>
        </div>
    </div>
</div>

Areas/Admin/Views/GameMatch/Index.cshtml
@model IEnumerable<ProjectPrototype.ViewModels.GameMatch>

@{
    ViewData["Title"] = "Games";
}

<div class="jace-container">
    <h1 class="table-title">Games</h1>
    <hr />
    <a class="table-management-button" asp-action="Index" asp-controller="Home">Go Back Home</a>
    <a class="table-management-button" asp-controller="GameMatch" asp-action="Create">Create New</a>
    <form asp-controller="GameMatch" asp-action="Index">
        <input class="filter text-input" type="text" name="SearchString" />
        <input class="filter table-management-button" type="submit" value="Filter" />
    </form>
    <form action="Controllers/GamesController" method="post">
        <div>
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            Winner
                        </th>
                        <th>
                            Winner Score
                        </th>
                        <th>
                            Loser
                        </th>
                        <th>
                            Loser Score
                        </th>
                        <th>
                            Date/Time
                        </th>
                        <th>
                            Location
                        </th>
                        <th>

                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.TeamW.TeamName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.MatchW.Score)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TeamL.TeamName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.MatchL.Score)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Game.DateTime)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Game.Location)
                            </td>
                            <td>
                                <a class="table-management-button" asp-controller="GameMatch" asp-action="Edit" asp-route-Id="@item.Game.GameId">Edit</a>
                                <a class="table-management-button" asp-controller="GameMatch" asp-action="Stats" asp-route-Id="@item.Game.GameId">Details</a>
                                <a class="table-management-button" asp-controller="GameMatch" asp-action="Delete" asp-route-Id="@item.Game.GameId">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </form>
    <form asp-action="SimulateSeason">
        <div>
            Simulate Season <input class="text-input" type="number" name="year" />
            <input type="submit" value="Simulate" class="table-management-button" />
        </div>
    </form>
</div>